name: rick_morty
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-76.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  icons_plus: ^3.0.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  http: ^0.13.5
  pull_to_refresh: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/svg/


  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
